# NOTE: you may need to pin `crc = { version = "=3.3.0" }` if you keep running into errors on upgrades
# The issue is that lzma-rust2 v15.4.0 mandated crc 3.3.0 precise, but sqlx keeps updating it to 3.4.0

[workspace]
resolver = "3"
members = ["audit", "audit_macro"]

[workspace.dependencies]
async-trait = "0.1.89"
audit_macro = { path = "./audit_macro", version = "0.1.0" }
axum = { version = "0.8.8" }
axum-extra = { version = "0.12.5", features = ["cookie", "typed-header"] }
axum-login = "0.18.0"
axum-macros = { version = "0.5.0" }
base64ct = { version = "1.8.3", features = ["alloc"] }
# TODO: switch to jiff https://github.com/BurntSushi/jiff
chrono = { version = "0.4.44", features = ["serde"] }
console_error_panic_hook = "0.1.7"
dotenvy = "0.15.7"
futures = "0.3.32"
garde = { version = "0.22.1", features = ["derive", "email"] }
http = "1.4.0"
leptos = { version = "0.8.17", features = ["nightly"] }
leptos_axum = { version = "0.8.8" }
leptos_meta = { version = "0.8.6" }
leptos_router = { version = "0.8.13", features = ["nightly"] }
mailgun-rs = { version = "2.0.2" }
# TODO: switch to pulldown-cmark https://github.com/pulldown-cmark/pulldown-cmark/
markdown = "1.0.0"
oauth2 = "5.0.0"
openidconnect = "4.0.1"
plotly = { version = "0.14.1", features = ["static_export_default"] }
proc-macro2 = "1.0.106"
quote = "1.0.45"
rand = { version = "0.10.0" }
reactive_stores = "0.4.2"
reqwest = { version = "0.13.2", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = { version = "0.11.0", default-features = false }
syn = "2.0.117"

sqlx = {
    version = "0.8.6",
    features = [
        "chrono",
        "derive",
        "json",
        "macros",
        "migrate",
        "postgres",
        "runtime-tokio",
        "time",
        "tls-rustls",
        "uuid",
    ]
}

thiserror = "2.0.18"
time = { version = "0.3.47", features = ["formatting", "macros", "parsing"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.6.8", features = ["fs"] }
tracing = { version = "0.1.44" }
uuid = { version = "1.23.0", features = ["serde"] }
wasm-bindgen = "0.2.117"

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
