# Multiple steps are required to get leptosfmt working correctly:
# 1. `rustfmt.toml` must contain the `edition` key — actually it looks like this was only true until edition 2024 stabilised, as I have now removed it.
# 2. `rust-analyzer.toml` must contain the override command invoking `leptosfmt`
# 3. `leptosfmt.toml` must contain your preferred settings
#
# Available options:
# https://github.com/bram209/leptosfmt/blob/main/docs/configuration.md

attr_value_brace_style = "WhenRequired"
indentation_style = "Spaces"
macro_names = ["leptos::view", "view"]
max_width = 100
newline_style = "Unix"
