fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "One"
imports_granularity = "Crate"
reorder_impl_items = true
trailing_comma = "Always"
use_field_init_shorthand = true
where_single_line = true

