comment_width = 100
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "One"
imports_granularity = "Crate"
inline_attribute_width = 100
reorder_impl_items = true
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
