comment_width = 100
condense_wildcard_suffixes = true
edition = "2024"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
inline_attribute_width = 100
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
