// mod error;
mod add;
mod app;
mod gateway;
mod instructions;
mod landing;
mod list;
mod protected;
mod report;
mod review;
mod sign_up;
mod terms;

// pub use error::*;
pub use add::*;
pub use app::*;
pub use gateway::*;
pub use instructions::*;
pub use landing::*;
pub use list::*;
pub use protected::*;
pub use report::*;
pub use review::*;
pub use sign_up::*;
pub use terms::*;
